# Generated by Django 3.2 on 2023-02-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_title_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default='sample text', max_length=2000, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
