# Generated by Django 3.2 on 2023-02-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230217_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
