# Generated by Django 3.2 on 2023-02-17 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_second_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
