# Generated by Django 3.2 on 2023-02-18 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_remove_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
