# Generated by Django 3.2 on 2023-02-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_auto_20230219_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
